
on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.5
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      run: go build
    - name: Test
      run: go test ./...
